/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConversionProgress: typeof import('./../components/ConversionProgress.vue')['default']
    ConversionResults: typeof import('./../components/ConversionResults.vue')['default']
    ConversionSizeTotals: typeof import('./../components/ConversionSizeTotals.vue')['default']
    ConverterWorkspace: typeof import('./../components/ConverterWorkspace.vue')['default']
  }
}
